name:                arrowgant
version:             0.2.0.0
github:              "foshardware/arrowgant"
license:             BSD3
author:              "Andreas Westerwick"
maintainer:          "westerwick@pconas.de"
copyright:           "2019 Andreas Westerwick"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- arrows
- hashable
- lens
- mtl
- unordered-containers
- vector

library:
  source-dirs: src

tests:
  arrowgant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arrowgant
    - arrows
    - tasty
    - tasty-hunit
