name:                arrowgant
version:             0.2.0.1
github:              "foshardware/arrowgant"
license:             BSD3
author:              "Andreas Westerwick"
maintainer:          "westerwick@pconas.de"
copyright:           "2019 Andreas Westerwick"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- arrows
- base >= 4.9.2 && < 5
- arrows
- hashable
- lens
- mtl
- tasty
- tasty-hunit
- unordered-containers
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2

tests:
  arrowgant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O
    - -threaded
    - -rtsopts
    dependencies:
    - arrowgant
