name:                arrowgant
version:             0.1.0.1
github:              "foshardware/arrowgant"
license:             BSD3
author:              "Andreas Westerwick"
maintainer:          "westerwick@pconas.de"
copyright:           "2019 Andreas Westerwick"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/arrowgant#readme>

dependencies:
- base >= 4.7 && < 5
- arrows
- containers
- mtl
- vector

library:
  source-dirs: src

tests:
  arrowgant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arrowgant
    - arrows
    - tasty
    - tasty-hunit
